var searchData=
[
  ['linear_20algebra_20operators',['Linear algebra operators',['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html',1,'']]],
  ['lambert',['Lambert',['../classLambert.html',1,'Lambert'],['../classLambert.html#ad54321354ec581f5684fd9336f5d48c8',1,'Lambert::Lambert()']]],
  ['lambert_2eh',['lambert.h',['../lambert_8h.html',1,'']]],
  ['length',['Length',['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html#gae825111f1aec288c58b7f591e5f28550',1,'Length(const Vec2f &amp;i_vector)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html#gaf4665ed9ce458687b4f37b51c4078e7b',1,'Length(const Vec3f &amp;i_vector)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html#gae514c75c328a3b108c318edbe88b8a05',1,'Length(const Vec4f &amp;i_vector)(Global Namespace)']]],
  ['length_2eh',['length.h',['https://moddyz.github.io/GraphicsMath/length_8h.html',1,'']]],
  ['lengthsquared',['LengthSquared',['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html#ga3ac710c8671238bedf0874b8872ec9c8',1,'LengthSquared(const Vec2f &amp;i_vector)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html#gad6acf90cacc7350af1049a0d7986ad0e',1,'LengthSquared(const Vec3f &amp;i_vector)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__linearAlgebra.html#ga6f89cbf4ef1dbea9c41f55d603adb910',1,'LengthSquared(const Vec4f &amp;i_vector)(Global Namespace)']]],
  ['lengthsquared_2eh',['lengthSquared.h',['https://moddyz.github.io/GraphicsMath/lengthSquared_8h.html',1,'']]],
  ['linearinterpolation',['LinearInterpolation',['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga277d2156d5ef3de29f2ba6d14e3d0bf2',1,'LinearInterpolation(const float &amp;i_source, const float &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga18cff1ac7be5e714cb3bec000a23597e',1,'LinearInterpolation(const Mat3f &amp;i_source, const Mat3f &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga2a4930dc49ff92002803e09977e7ea79',1,'LinearInterpolation(const Mat4f &amp;i_source, const Mat4f &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#gae16b73ed33599600ce0f63609ea29280',1,'LinearInterpolation(const Vec2f &amp;i_source, const Vec2f &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#gad488515696b51df72e6fcabf184b668e',1,'LinearInterpolation(const Vec3f &amp;i_source, const Vec3f &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#gab7fb01b198f2b3a97ff16317f4137f00',1,'LinearInterpolation(const Vec4f &amp;i_source, const Vec4f &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga9f7ba4fb41c5691a18ed77e018b1df7f',1,'LinearInterpolation(const Vec2fRange &amp;i_source, const Vec2fRange &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga6984c2cc7aacf009a92815fc3d05857d',1,'LinearInterpolation(const Vec3fRange &amp;i_source, const Vec3fRange &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga566b57bd3580d90b47fdf9acebafb40c',1,'LinearInterpolation(const Vec4fRange &amp;i_source, const Vec4fRange &amp;i_target, const float &amp;i_weight)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#gaf464a50551f76bfe805db197ec896559',1,'LinearInterpolation(const FloatRange &amp;i_source, const FloatRange &amp;i_target, const float &amp;i_weight)(Global Namespace)']]],
  ['linearinterpolation_2eh',['linearInterpolation.h',['https://moddyz.github.io/GraphicsMath/linearInterpolation_8h.html',1,'']]],
  ['linearmap',['LinearMap',['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga5798f027478c55bade52df30921e7982',1,'LinearMap(const float &amp;i_sourceValue, const FloatRange &amp;i_sourceRange, const FloatRange &amp;i_targetRange)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga263b14faec42590b79c9279ab3f1ad99',1,'LinearMap(const Mat3f &amp;i_sourceValue, const FloatRange &amp;i_sourceRange, const FloatRange &amp;i_targetRange)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga1eb7b9b44b3def2bcbc54ca6ec198b2b',1,'LinearMap(const Mat4f &amp;i_sourceValue, const FloatRange &amp;i_sourceRange, const FloatRange &amp;i_targetRange)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga5fcee0bde103f8a7f117a6a48c6a94c1',1,'LinearMap(const Vec2f &amp;i_sourceValue, const FloatRange &amp;i_sourceRange, const FloatRange &amp;i_targetRange)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#gae2b1e291707e7fcf0896da548ca64976',1,'LinearMap(const Vec3f &amp;i_sourceValue, const FloatRange &amp;i_sourceRange, const FloatRange &amp;i_targetRange)(Global Namespace)'],['https://moddyz.github.io/GraphicsMath/group__gm__functions__basic.html#ga8128bd11dd098ac73ed334771d311fd1',1,'LinearMap(const Vec4f &amp;i_sourceValue, const FloatRange &amp;i_sourceRange, const FloatRange &amp;i_targetRange)(Global Namespace)']]],
  ['linearmap_2eh',['linearMap.h',['https://moddyz.github.io/GraphicsMath/linearMap_8h.html',1,'']]],
  ['log_2eh',['log.h',['https://moddyz.github.io/GraphicsMath/log_8h.html',1,'']]]
];
